### ISSUE TITLE
Examples broken in python 2

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#34]
Running `pyglet_demo.py` or `pyglet_demo2.py` in python 2 triggers `TypeError` related to unbound methods. I guess this is related to the separation of the visualization and the fact that python 3 don't have unbound functions. Not a big problem for me personally. I stumbled over it when testing py2 compatibility since this package doesn't really state anywhere what is supported.

```
$ python pyglet_demo.py
Traceback (most recent call last):
  File "pyglet_demo.py", line 14, in <module>
    meshes = pywavefront.Wavefront('uv_sphere.obj')
  File "../pywavefront/__init__.py", line 51, in __init__
    ObjParser(self, self.file_name)
  File "../pywavefront/__init__.py", line 72, in __init__
    self.read_file(file_name)
  File "../pywavefront/parser.py", line 46, in read_file
    self.parse(line, dir=os.path.dirname(file_name))
  File "../pywavefront/parser.py", line 75, in parse
    parse_function(args)
  File "../pywavefront/__init__.py", line 86, in parse_mtllib
    materials = material.MaterialParser(mtllib).materials
  File "../pywavefront/material.py", line 102, in __init__
    self.read_file(file_path)
  File "../pywavefront/parser.py", line 46, in read_file
    self.parse(line, dir=os.path.dirname(file_name))
  File "../pywavefront/parser.py", line 75, in parse
    parse_function(args)
  File "../pywavefront/material.py", line 131, in parse_map_Kd
    self.this_material.set_texture(Kd)
  File "../pywavefront/material.py", line 82, in set_texture
    self.texture = texture.Texture(path)
TypeError: unbound method init() must be called with _Texture instance as first argument (got str instance instead)
```

**Comment by einarf** [comment]
Fixed. Will make PR once my last ones are merged.

**Comment by greenmoss** [comment]
Great! Thanks for the report.
