### ISSUE TITLE
Pyglet examples fail in Python 3.7.0

### ISSUE THREAD

**Issue by sjml** [greenmoss/PyWavefront#71]
I've got a copy of [the example directory](https://github.com/greenmoss/PyWavefront/tree/master/example) and am trying to run the example scripts there.

The Pyglet demos work fine if I run them in Python 2, like so:

```
$ python --version
Python 2.7.15
$ virtualenv env2
[...]
$ . env2/bin/activate
$ pip install pyglet PyWavefront
[...]
$ python pyglet_demo.py
```

But in Python 3, I get the following exception and stack trace: 

```
$ python --version
Python 3.7.0
$ virtualenv env3
[...]
$ . env3/bin/activate
$ pip install pyglet PyWavefront
[...]
$ python pyglet_demo.py
Traceback (most recent call last):
  File "/Users/shane/Projects/pyglet/env3/lib/python3.7/site-packages/pywavefront/obj.py", line 379, in consume_faces
    self.next_line()
  File "/Users/shane/Projects/pyglet/env3/lib/python3.7/site-packages/pywavefront/parser.py", line 106, in next_line
    self.line = next(self.lines)  # Will raise StopIteration when there are no more lines
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyglet_demo.py", line 15, in <module>
    meshes = pywavefront.Wavefront('uv_sphere.obj')
  File "/Users/shane/Projects/pyglet/env3/lib/python3.7/site-packages/pywavefront/wavefront.py", line 67, in __init__
    cache=cache)
  File "/Users/shane/Projects/pyglet/env3/lib/python3.7/site-packages/pywavefront/obj.py", line 80, in __init__
    self.parse()
  File "/Users/shane/Projects/pyglet/env3/lib/python3.7/site-packages/pywavefront/obj.py", line 90, in parse
    super(ObjParser, self).parse()
  File "/Users/shane/Projects/pyglet/env3/lib/python3.7/site-packages/pywavefront/parser.py", line 136, in parse
    self.dispatcher.get(self.values[0], self.parse_fallback)()
  File "/Users/shane/Projects/pyglet/env3/lib/python3.7/site-packages/pywavefront/obj.py", line 252, in parse_f
    self.material.vertices += list(self.consume_faces())
RuntimeError: generator raised StopIteration
```

This may be something new to Python 3.7.0, but I'm not sure what might have changed to break this. :-/

**Comment by einarf** [comment]
This is because of the ``StopIteration`` changes in py37 https://www.python.org/dev/peps/pep-0479/

Should be easy enough to fix. I can take a look shortly.

**Comment by einarf** [comment]
Fix now in PR #72

**Comment by einarf** [comment]
For people with less patience: 
```
pip install https://github.com/einarf/PyWavefront/archive/py37-support.zip
```

**Comment by greenmoss** [comment]
Merged; thanks for report and fix!
